export const REGISTER_USER = "ENREGISTRER_UTILISATEUR";
export const LOGIN_USER = "CONNEXION_UTILISATEUR";
export const LOAD_USER = "CHARGER_UTILISATEUR";
export const FAIL_USER = "ECHEC_UTILISATEUR";
export const LOGOUT_USER = "DECONNEXION_UTILISATEUR";
export const CURRENT_USER = "UTILISATEUR_ACTUEL";